before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: bgki9uOX9m3xb8GRww4cHZ5+N/BjRpT2KLjW0wvq+jrp3QYOGxfzbxF0mAn5Eu6IirNKZ/cZ4nVjGOSx9TaS1MvRK2UJ4s7FYRlXx2PHNrTONy8Qo3GOmYwG67hvdKXjwavjEK325hNNTGOfpZ+XrSNz19T2nUVrk8FIf+UleFHcEZYLiOnJPnMSYZnZo0toC0mIbihBvo87tIWKHM0Q9K9Gh96phwMf7Ey8hD98ZVvY/6F+7IhygdfEsKUjIWaL+reZMHIHcsTGT1Q3T6O9RBFDrhU1J+GkNanTpaC1BxI9Xs7gMCUAmDMgfzTqpWc2r6PuHFKjFdQ0PxtTcnl5Q0rPaSYfbvyzlQ6rBkgDwgSFZWkQE5chmIdoxsF+UBL1eCoYFiFRp/wIDBiI3eEPUzgEYQgaQ9HWM1DEtAaXR56I1vPnvQje/boMC5R6R/EwB4BNbtu67HBso02kk23L/s3j4GLXFxx+gyRUq0K7szqWXEO2vPMRkIziCWWz2WPbkRHNjAhSWiep5wMEelqESI03sHwNYWXGFMbaErWfVeSZpSpVv6ifyd3eo09x8StNL9F5HW+Cau8eIm/WeiBS+kOqAj29zfCdBAj58G5r0fH0pNRviOVEQOyiwbuFw2qYOiYuJ/SXnX5ydq70pEuMNCOZl7Wdy/RrbwUGOfFHprc= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
